
version: 2

macros:
  - name: build_key_from_columns
    description: For each row of data, this macro grabs each value from all the columns, except the columns we specify in the exclude list. 
    arguments:
      - name: table_name
        type: string
        description: The name of the table
      - name: exclude
        type: list
        description: List of columns to exclude from the key (e.g. if you dont want to track them for SCD2)
  - name: join_snapshots
    description: '{{ doc("join_snapshots") }}'
    arguments:
      - name: cte_join
        type: string
        description: The table that is creating the spine of your final model
      - name: cte_join_on
        type: string
        description: The new table you’re joining onto the spine. 
      - name: cte_join_valid_to
        type: string
        description: TODO 
      - name: cte_join_valid_from
        type: string
        description: TODO 
      - name: cte_join_on_valid_to
        type: string
        description: TODO 
      - name: cte_join_on_valid_from
        type: string
        description: TODO 
      - name: cte_join_id
        type: string
        description: TODO 
      - name: cte_join_on_id
        type: string
        description: TODO 

models:
  - name: stg_product_important_status
    columns:
      - name: grain_id
        tests:
          - unique
          - not_null

# models:
#   - name: my_first_dbt_model
#     description: "A starter dbt model"
#     columns:
#       - name: id
#         description: "The primary key for this table"
#         tests:
#           - unique
#           - not_null

#   - name: my_second_dbt_model
#     description: "A starter dbt model"
#     columns:
#       - name: id
#         description: "The primary key for this table"
#         tests:
#           - unique
#           - not_null
